apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: ai-interview-assistant
  labels:
    app: ai-interview-assistant
    component: frontend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: ai-interview-assistant
    component: frontend
