import PDFDocument from 'pdfkit';
import { Types } from 'mongoose';
import { Interview } from '../models/Interview';
import { Feedback } from '../models/Feedback';
import { StudyPlan } from '../models/StudyPlan';
import { User } from '../models/User';
import { AppError } from '../middleware/errorHandler';
import { ERROR_CODES, HTTP_STATUS } from '../utils/constants';
import { formatDuration, getScoreLabel } from '../utils/helpers';

class ExportService {
  async exportInterviewReport(interviewId: string): Promise<Buffer> {
    const interview = await Interview.findById(interviewId).populate('userId', 'username email');
    if (!interview) {
      throw new AppError('Interview not found', HTTP_STATUS.NOT_FOUND, ERROR_CODES.NOT_FOUND);
    }

    const feedbacks = await Feedback.find({ interviewId: new Types.ObjectId(interviewId) });
    const user = interview.userId as any;

    return new Promise<Buffer>((resolve, reject) => {
      const doc = new PDFDocument({
        size: 'A4',
        margins: { top: 50, bottom: 50, left: 50, right: 50 },
        info: {
          Title: `Interview Report - ${interview._id}`,
          Author: 'AI Interview Assistant',
          Subject: `Interview Report - ${interview.type}`,
        },
      });

      const chunks: Buffer[] = [];
      doc.on('data', (chunk: Buffer) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      this.addHeader(doc, 'Interview Report');
      this.addSubHeader(doc, `Candidate: ${user?.username || 'N/A'}`);

      doc.fontSize(10).text(`Email: ${user?.email || 'N/A'}`, { align: 'left' });
      doc.text(`Date: ${interview.createdAt.toLocaleDateString()}`);
      doc.text(`Type: ${interview.type} | Difficulty: ${interview.difficulty}`);
      doc.text(`Status: ${interview.status} | Duration: ${interview.duration ? formatDuration(interview.duration) : 'N/A'}`);
      doc.moveDown();

      if (interview.overallScore !== undefined) {
        this.addScoreSection(doc, 'Overall Performance', interview.overallScore);
      }

      doc.moveDown();
      doc.fontSize(14).font('Helvetica-Bold').text('Strengths', { underline: true });
      doc.fontSize(10).font('Helvetica');
      (interview.strengths || []).forEach(s => doc.text(`  • ${s}`));
      doc.moveDown();

      doc.fontSize(14).font('Helvetica-Bold').text('Areas for Improvement', { underline: true });
      doc.fontSize(10).font('Helvetica');
      (interview.weaknesses || []).forEach(w => doc.text(`  • ${w}`));
      doc.moveDown();

      doc.fontSize(14).font('Helvetica-Bold').text('Question Breakdown', { underline: true });
      doc.moveDown(0.5);

      for (let i = 0; i < interview.questions.length; i++) {
        const q = interview.questions[i];
        const feedback = feedbacks.find(f => f.questionId.equals(q.questionId));

        doc.fontSize(11).font('Helvetica-Bold').text(`Q${i + 1}: ${q.question.substring(0, 100)}${q.question.length > 100 ? '...' : ''}`);
        if (q.score !== undefined) {
          doc.fontSize(10).font('Helvetica').text(`Score: ${q.score}/100 (${getScoreLabel(q.score)})`);
        }
        if (feedback) {
          if (feedback.strengths.length > 0) {
            doc.fontSize(9).text(`Strengths: ${feedback.strengths.slice(0, 2).join(', ')}`);
          }
          if (feedback.weaknesses.length > 0) {
            doc.fontSize(9).text(`Weaknesses: ${feedback.weaknesses.slice(0, 2).join(', ')}`);
          }
        }
        doc.moveDown(0.3);
      }

      const footerText = 'Generated by AI Interview Assistant';
      doc.fontSize(8).font('Helvetica').text(footerText, 50, doc.page.height - 50, { align: 'center' });

      doc.end();
    });
  }

  async exportStudyPlan(planId: string): Promise<Buffer> {
    const plan = await StudyPlan.findById(planId).populate('userId', 'username email');
    if (!plan) {
      throw new AppError('Study plan not found', HTTP_STATUS.NOT_FOUND, ERROR_CODES.NOT_FOUND);
    }

    const user = plan.userId as any;

    return new Promise<Buffer>((resolve, reject) => {
      const doc = new PDFDocument({
        size: 'A4',
        margins: { top: 50, bottom: 50, left: 50, right: 50 },
        info: {
          Title: `Study Plan - ${plan.title}`,
          Author: 'AI Interview Assistant',
        },
      });

      const chunks: Buffer[] = [];
      doc.on('data', (chunk: Buffer) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      this.addHeader(doc, plan.title);
      this.addSubHeader(doc, `Prepared for: ${user?.username || 'N/A'}`);

      doc.fontSize(10).text(plan.description);
      doc.moveDown();

      doc.fontSize(14).font('Helvetica-Bold').text('Goals');
      doc.fontSize(10).font('Helvetica');
      plan.goals.forEach(g => doc.text(`  • ${g}`));
      doc.moveDown();

      doc.fontSize(14).font('Helvetica-Bold').text(`Progress: ${plan.progress.overallPercentage}% complete`);
      doc.fontSize(10).font('Helvetica');
      doc.text(`Topics completed: ${plan.progress.topicsCompleted}/${plan.topics.length}`);
      doc.text(`Hours spent: ${plan.progress.hoursSpent}`);
      doc.moveDown();

      doc.fontSize(14).font('Helvetica-Bold').text('Topics', { underline: true });
      doc.moveDown(0.5);

      for (const topic of plan.topics) {
        const statusIcon = topic.status === 'completed' ? '✓' : topic.status === 'in-progress' ? '◷' : '○';
        doc.fontSize(11).font('Helvetica-Bold').text(`${statusIcon} ${topic.name}`);
        doc.fontSize(9).font('Helvetica').text(`  Priority: ${topic.priority} | Status: ${topic.status}`);
        if (topic.resources.length > 0) {
          doc.text(`  Resources: ${topic.resources.join(', ')}`);
        }
        doc.moveDown(0.3);
      }

      doc.fontSize(14).font('Helvetica-Bold').text('Schedule', { underline: true });
      doc.moveDown(0.5);

      for (const entry of plan.schedule.slice(0, 20)) {
        const date = new Date(entry.date).toLocaleDateString();
        const done = entry.completed ? '✓' : '○';
        doc.fontSize(9).font('Helvetica').text(`${done} ${date} - ${entry.topic} (${entry.duration}min)`);
      }

      if (plan.schedule.length > 20) {
        doc.fontSize(9).text(`... and ${plan.schedule.length - 20} more scheduled items`);
      }

      doc.fontSize(8).font('Helvetica').text('Generated by AI Interview Assistant', 50, doc.page.height - 50, { align: 'center' });

      doc.end();
    });
  }

  async exportPerformanceAnalytics(userId: string, period: '7d' | '30d' | '90d' | 'all' = '30d'): Promise<Buffer> {
    const user = await User.findById(userId);
    if (!user) {
      throw new AppError('User not found', HTTP_STATUS.NOT_FOUND, ERROR_CODES.NOT_FOUND);
    }

    const now = new Date();
    let startDate: Date;
    switch (period) {
      case '7d': startDate = new Date(now.getTime() - 7 * 86400000); break;
      case '30d': startDate = new Date(now.getTime() - 30 * 86400000); break;
      case '90d': startDate = new Date(now.getTime() - 90 * 86400000); break;
      default: startDate = new Date(0);
    }

    const interviews = await Interview.find({
      userId: new Types.ObjectId(userId),
      status: 'completed',
      completedAt: { $gte: startDate },
    }).sort({ completedAt: -1 });

    return new Promise<Buffer>((resolve, reject) => {
      const doc = new PDFDocument({
        size: 'A4',
        margins: { top: 50, bottom: 50, left: 50, right: 50 },
        info: {
          Title: `Performance Analytics - ${user.username}`,
          Author: 'AI Interview Assistant',
        },
      });

      const chunks: Buffer[] = [];
      doc.on('data', (chunk: Buffer) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      this.addHeader(doc, 'Performance Analytics');
      this.addSubHeader(doc, `User: ${user.username} (${user.email})`);
      doc.fontSize(10).text(`Period: ${period} | Interviews: ${interviews.length}`);
      doc.moveDown();

      if (interviews.length > 0) {
        const scores = interviews.map(i => i.overallScore || 0).filter(s => s > 0);
        const avgScore = scores.length > 0 ? Math.round(scores.reduce((a, b) => a + b, 0) / scores.length) : 0;
        const bestScore = Math.max(...scores, 0);
        const worstScore = Math.min(...scores, 100);

        this.addScoreSection(doc, 'Average Score', avgScore);
        doc.fontSize(10).font('Helvetica').text(`Best Score: ${bestScore}`);
        doc.text(`Worst Score: ${worstScore}`);
        doc.moveDown();

        doc.fontSize(14).font('Helvetica-Bold').text('Interview History', { underline: true });
        doc.moveDown(0.5);

        for (const interview of interviews.slice(0, 15)) {
          const date = interview.completedAt?.toLocaleDateString() || 'N/A';
          doc.fontSize(10).font('Helvetica').text(
            `${date} | ${interview.type} (${interview.difficulty}) | Score: ${interview.overallScore || 'N/A'} | Duration: ${interview.duration ? formatDuration(interview.duration) : 'N/A'}`
          );
        }

        if (interviews.length > 15) {
          doc.fontSize(9).text(`... and ${interviews.length - 15} more interviews`);
        }

        const byType: Record<string, number[]> = {};
        for (const interview of interviews) {
          if (interview.overallScore !== undefined) {
            if (!byType[interview.type]) byType[interview.type] = [];
            byType[interview.type].push(interview.overallScore);
          }
        }

        doc.moveDown();
        doc.fontSize(14).font('Helvetica-Bold').text('Performance by Category', { underline: true });
        doc.moveDown(0.5);

        for (const [type, typeScores] of Object.entries(byType)) {
          const typeAvg = Math.round(typeScores.reduce((a, b) => a + b, 0) / typeScores.length);
          doc.fontSize(10).font('Helvetica').text(`${type}: ${typeAvg}/100 (${typeScores.length} interviews)`);
        }
      } else {
        doc.fontSize(12).text('No interview data available for the selected period.');
      }

      doc.fontSize(8).font('Helvetica').text('Generated by AI Interview Assistant', 50, doc.page.height - 50, { align: 'center' });

      doc.end();
    });
  }

  private addHeader(doc: PDFKit.PDFDocument, title: string): void {
    doc.fontSize(22).font('Helvetica-Bold').text(title, { align: 'center' });
    doc.moveDown(0.5);
    doc.strokeColor('#4A90D9').lineWidth(2).moveTo(50, doc.y).lineTo(545, doc.y).stroke();
    doc.moveDown();
  }

  private addSubHeader(doc: PDFKit.PDFDocument, subTitle: string): void {
    doc.fontSize(12).font('Helvetica').text(subTitle, { align: 'center' });
    doc.moveDown();
  }

  private addScoreSection(doc: PDFKit.PDFDocument, label: string, score: number): void {
    const color = score >= 75 ? '#27AE60' : score >= 50 ? '#F39C12' : '#E74C3C';

    doc.fontSize(14).font('Helvetica-Bold').text(label);
    doc.fontSize(24).font('Helvetica-Bold').fillColor(color).text(`${score}/100`, { align: 'center' });
    doc.fontSize(10).font('Helvetica').fillColor('#333').text(getScoreLabel(score), { align: 'center' });
    doc.moveDown();
  }
}

export const exportService = new ExportService();
export default exportService;
